use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Game {
    pub id: String,
    pub name: String,
    pub description: String,
    pub min_players: u32,
    pub max_players: u32,
    pub duration_minutes: u32,
    pub difficulty: String,
    pub tags: Vec<String>,
    pub icon: String,
    pub online_count: u32,
    pub room_count: u32,
    pub hot: bool,
}

impl Game {
    pub fn preset_list() -> Vec<Game> {
        vec![
            Game {
                id: "avalon".into(),
                name: "阿瓦隆".into(),
                description: "隐藏身份与推理的经典桌游，玩家分为正义与邪恶两方，通过任务和投票决出胜负。".into(),
                min_players: 5,
                max_players: 10,
                duration_minutes: 30,
                difficulty: "中等".into(),
                tags: vec!["推理".into(), "身份隐藏".into(), "团队".into()],
                icon: "🛡️".into(),
                online_count: 245,
                room_count: 32,
                hot: true,
            },
            Game {
                id: "werewolf".into(),
                name: "狼人杀".into(),
                description: "经典社交推理游戏，村民与狼人之间的对决，需要口才和逻辑推理。".into(),
                min_players: 8,
                max_players: 18,
                duration_minutes: 45,
                difficulty: "简单".into(),
                tags: vec!["推理".into(), "社交".into(), "身份隐藏".into()],
                icon: "🐺".into(),
                online_count: 512,
                room_count: 68,
                hot: true,
            },
            Game {
                id: "splendor".into(),
                name: "璀璨宝石".into(),
                description: "文艺复兴时期的宝石商人，收集宝石、发展产业、获得贵族青睐。".into(),
                min_players: 2,
                max_players: 4,
                duration_minutes: 30,
                difficulty: "简单".into(),
                tags: vec!["策略".into(), "卡牌".into(), "经济".into()],
                icon: "💎".into(),
                online_count: 128,
                room_count: 18,
                hot: false,
            },
            Game {
                id: "catan".into(),
                name: "卡坦岛".into(),
                description: "在卡坦岛上开拓殖民，通过交易和建设成为最成功的拓荒者。".into(),
                min_players: 3,
                max_players: 4,
                duration_minutes: 60,
                difficulty: "中等".into(),
                tags: vec!["策略".into(), "交易".into(), "建设".into()],
                icon: "🏝️".into(),
                online_count: 189,
                room_count: 24,
                hot: true,
            },
            Game {
                id: "codenames".into(),
                name: "行动代号".into(),
                description: "两队间谍通过代号猜测己方特工，考验联想和默契。".into(),
                min_players: 4,
                max_players: 8,
                duration_minutes: 15,
                difficulty: "简单".into(),
                tags: vec!["词汇".into(), "团队".into(), "推理".into()],
                icon: "🕵️".into(),
                online_count: 98,
                room_count: 12,
                hot: false,
            },
            Game {
                id: "unocards".into(),
                name: "UNO牌".into(),
                description: "经典卡牌游戏，抢先出完手中所有牌，用功能牌逆转局势。".into(),
                min_players: 2,
                max_players: 10,
                duration_minutes: 20,
                difficulty: "简单".into(),
                tags: vec!["卡牌".into(), "休闲".into(), "派对".into()],
                icon: "🃏".into(),
                online_count: 367,
                room_count: 45,
                hot: true,
            },
        ]
    }
}
